// PM2 Ecosystem Configuration
// Auto-generated by Wingman - do not edit manually
module.exports = {
  "apps": [
    {
      "name": "honest-ivory-thicket-app-super-based-todo",
      "script": "bash",
      "args": [
        "-c",
        "PORT=41000 bunx vite --host"
      ],
      "cwd": "/Users/mini/code/todo-starter",
      "env": {
        "APP_ID": "8287d962-479d-4f35-aa5e-1a35ced77041",
        "APP_LABEL": "Super Based Todo",
        "USER_ALIAS": "honest-ivory-thicket",
        "PORT": "41000"
      },
      "out_file": "/Users/mini/code/todo-starter/apps/logs/honest-ivory-thicket-app-super-based-todo-out.log",
      "error_file": "/Users/mini/code/todo-starter/apps/logs/honest-ivory-thicket-app-super-based-todo-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    }
  ]
};
